# Generated by Django 3.2.3 on 2021-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
