# Generated by Django 3.2.3 on 2021-05-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_alter_issue_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
